global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "marl_app"
    static_configs:
      - targets: ["localhost:9091"]

rule_files:
  - "/etc/prometheus/alert_rules.yml"
